# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnab < Formula
  desc "GreenNode AgentBase CLI"
  homepage "https://github.com/vngcloud/gnab-releases"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.5/gnab_1.0.5_darwin_amd64.tar.gz"
      sha256 "34f268009ae52fe57790c75bfddad46d5e8cdb649b2c649b0e70fc0230b8df8d"

      define_method(:install) do
        bin.install "gnab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.5/gnab_1.0.5_darwin_arm64.tar.gz"
      sha256 "7bc41814dd1457b85782105d519ff21d3f5b617a445eeea97566432b9da3e5e8"

      define_method(:install) do
        bin.install "gnab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.5/gnab_1.0.5_linux_amd64.tar.gz"
      sha256 "717ab1fa7c0d330b580843ac45d18287efdf13be22ba309c0cb056f8b734664b"
      define_method(:install) do
        bin.install "gnab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.5/gnab_1.0.5_linux_arm64.tar.gz"
      sha256 "e8ee37b69a8aad0caa8ba1102424728db791bf7769d6682c542cf8f380ef41d3"
      define_method(:install) do
        bin.install "gnab"
      end
    end
  end
end
