# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnab < Formula
  desc "GreenNode AgentBase CLI"
  homepage "https://github.com/vngcloud/gnab-releases"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.7/gnab_1.0.7_darwin_amd64.tar.gz"
      sha256 "d4eea47e55aa646f160bbb21956fedc2aa000f790d893a46c4a4e11cde51a134"

      define_method(:install) do
        bin.install "gnab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.7/gnab_1.0.7_darwin_arm64.tar.gz"
      sha256 "e11f76c3aa9d954f68a35930a8f00afbe379cffe712a7a57c95c57690a0c4a4e"

      define_method(:install) do
        bin.install "gnab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.7/gnab_1.0.7_linux_amd64.tar.gz"
      sha256 "75510a967ae115d0e4108ad53b31dc07121d71d8d8967375e9eebfbd21ccf3b8"
      define_method(:install) do
        bin.install "gnab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.7/gnab_1.0.7_linux_arm64.tar.gz"
      sha256 "d468f39b3b2f1b95dee2577c4cdb3c3ba152cf9a102ba7985b1a0bd232a5e028"
      define_method(:install) do
        bin.install "gnab"
      end
    end
  end
end
