# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnab < Formula
  desc "GreenNode AgentBase CLI"
  homepage "https://github.com/vngcloud/gnab-releases"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.8/gnab_1.0.8_darwin_amd64.tar.gz"
      sha256 "7e6bf913c8f82a9a4a99e601a79344420d0026480d5ffec34b3992dfe0d5abe7"

      define_method(:install) do
        bin.install "gnab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.8/gnab_1.0.8_darwin_arm64.tar.gz"
      sha256 "245fa8ad40b4bca8c56cd9238de4e25d200e255c34c61b278d732e4facd252aa"

      define_method(:install) do
        bin.install "gnab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.8/gnab_1.0.8_linux_amd64.tar.gz"
      sha256 "3a1f948cad5b1b7d95666e7bfc22034d3802df1f450f3a5e32b0a2e4acdf1887"
      define_method(:install) do
        bin.install "gnab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.8/gnab_1.0.8_linux_arm64.tar.gz"
      sha256 "b79ab14895e7ea7ec51f4c19e12399925ba8249b2cec71b78e2542a96a5b18bc"
      define_method(:install) do
        bin.install "gnab"
      end
    end
  end
end
