# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greennode < Formula
  desc "GreenNode AgentBase CLI"
  homepage "https://github.com/vngcloud/gnab-releases"
  version "1.0.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.15/greennode_1.0.15_darwin_amd64.tar.gz"
      sha256 "717870f3ee3569b1c229946a85f969c999c406a6c766d5e7f666440bc54fceb3"

      define_method(:install) do
        bin.install "greennode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.15/greennode_1.0.15_darwin_arm64.tar.gz"
      sha256 "737d797f12ca85a2cccfe50b2f87c4bc310528507fcf66922a1886b46dcd3c63"

      define_method(:install) do
        bin.install "greennode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.15/greennode_1.0.15_linux_amd64.tar.gz"
      sha256 "96b89d6cf6a1d004327ee1990779df22d9549f89043d520669f69669000df102"
      define_method(:install) do
        bin.install "greennode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.15/greennode_1.0.15_linux_arm64.tar.gz"
      sha256 "3a5e7b58b65852f2e4233aa07c87ef79ad665d1ff0fd2d4d2ffb1bb1181efc50"
      define_method(:install) do
        bin.install "greennode"
      end
    end
  end
end
