# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greennode < Formula
  desc "GreenNode AgentBase CLI"
  homepage "https://github.com/vngcloud/gnab-releases"
  version "1.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.14/greennode_1.0.14_darwin_amd64.tar.gz"
      sha256 "9ad75ec04298fdd6cef04b61ddb939b9b92ecb25eae46d36f2093172c83dd40f"

      define_method(:install) do
        bin.install "greennode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.14/greennode_1.0.14_darwin_arm64.tar.gz"
      sha256 "ab3028672837f448aa85131ad8640af740fe6a25b7fafc1b913c56e7ff2165ef"

      define_method(:install) do
        bin.install "greennode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.14/greennode_1.0.14_linux_amd64.tar.gz"
      sha256 "a0a55b960a399637dd03114dd4ebe8965a55fbd083f102045289f53298ebf74b"
      define_method(:install) do
        bin.install "greennode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.0.14/greennode_1.0.14_linux_arm64.tar.gz"
      sha256 "01af2986252cc7518b94c7289ae16c8edeb0e2cd0f299976ede92eae9699de8a"
      define_method(:install) do
        bin.install "greennode"
      end
    end
  end
end
