# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greennode < Formula
  desc "GreenNode AgentBase CLI"
  homepage "https://github.com/vngcloud/gnab-releases"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.1.0/greennode_1.1.0_darwin_amd64.tar.gz"
      sha256 "10387cd138b9005f00a98890b0ecc78e2e39aa9aa259ff15a11811b4c2e18188"

      define_method(:install) do
        bin.install "greennode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.1.0/greennode_1.1.0_darwin_arm64.tar.gz"
      sha256 "5c739edee9815f268f9eaf18a174f564eab786c8ebdc98937d2ee3eb3042507e"

      define_method(:install) do
        bin.install "greennode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.1.0/greennode_1.1.0_linux_amd64.tar.gz"
      sha256 "86f4199ec70683254c3c33b51e5f1e9a4b25742b9d4b4c485bdf86eb97508c81"
      define_method(:install) do
        bin.install "greennode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vngcloud/gnab-releases/releases/download/v1.1.0/greennode_1.1.0_linux_arm64.tar.gz"
      sha256 "9d07d29da8e1d05cc489cb7d57e21f985b8ef22e3cfe9c3ef9133441cad5189d"
      define_method(:install) do
        bin.install "greennode"
      end
    end
  end
end
